import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1c1b1d',
        'surface-container': '#201f21',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'surface-variant': '#353437',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#c5c9ae',
        'on-background': '#e5e1e4',
        primary: '#fbffe4',
        'primary-container': '#c5f02c',
        'primary-fixed': '#c7f32f',
        'primary-fixed-dim': '#add600',
        'on-primary-container': '#556b00',
        'on-primary': '#293500',
        secondary: '#98d2c5',
        'secondary-fixed-dim': '#98d2c5',
        'secondary-container': '#155249',
        'on-secondary': '#003730',
        'on-secondary-container': '#8ac3b7',
        tertiary: '#fefcfc',
        'on-tertiary': '#303031',
        'tertiary-container': '#e1e0e0',
        'on-tertiary-container': '#636363',
        outline: '#8e937a',
        'outline-variant': '#444934',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        technical: ['var(--font-ibm-mono)', 'ui-monospace', 'monospace'],
        label: ['var(--font-ibm-mono)', 'ui-monospace', 'monospace'],
      },
      backgroundImage: {
        'radial-glow':
          'radial-gradient(circle at top right, rgba(197,240,44,0.05), transparent 40%), radial-gradient(circle at bottom left, rgba(152,210,197,0.05), transparent 40%)',
      },
    },
  },
  plugins: [],
} satisfies Config;
