/**
 * Broadcast the OPEN flow end-to-end on mainnet with a throwaway wallet:
 *   1. Kamino deposit SOL collateral              (skippable)
 *   2. Kamino repay (partial / all / skip)        (only useful for reopen)
 *   3. Kamino borrow N USDC
 *   4. Mayan bridge USDC solana → base
 *   5. Poll explorer until ORDER_COMPLETED, confirm USDC on Base
 *
 * Secrets come from .env.test.local (generated by scripts/gen-test-wallets.ts).
 * RPC from apps/web/.env.local.
 *
 * Usage:
 *   pnpm tsx scripts/e2e-broadcast.ts                            # default 5 USDC
 *   pnpm tsx scripts/e2e-broadcast.ts --amount 15                # bridge 15 USDC
 *   pnpm tsx scripts/e2e-broadcast.ts --skip-deposit              # reuse on-chain collateral
 *   pnpm tsx scripts/e2e-broadcast.ts --skip-deposit --repay all --amount 15
 *     # reopen: repay existing debt, borrow 15 fresh, bridge 15
 *   pnpm tsx scripts/e2e-broadcast.ts --skip-deposit --skip-borrow --skip-bridge \
 *     --repay all --withdraw all
 *     # close-only: repay debt from wallet USDC, withdraw all collateral
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  Connection,
  Keypair,
  PublicKey,
  TransactionMessage,
  VersionedTransaction,
} from '@solana/web3.js';
import bs58 from 'bs58';
import { createPublicClient, http, erc20Abi } from 'viem';
import { base } from 'viem/chains';
import {
  BASE_USDC,
  DEFAULT_BORROW_USDC_UNITS,
  KAMINO_MAIN_MARKET,
  LAMPORTS_PER_SOL,
  SOLANA_USDC_MINT,
  TARGET_COLLATERAL_USD,
} from '@kast/shared';
import { createKaminoAdapter } from '@kast/kamino-adapter';
import { createMayanAdapter, type MayanAdapter, type Quote } from '@kast/mayan-adapter';
interface CliArgs {
  amount: bigint;
  skipDeposit: boolean;
  skipBorrow: boolean;
  skipBridge: boolean;
  repay: bigint | 'all' | null;
  withdraw: bigint | 'all' | null;
}

function parseCliArgs(): CliArgs {
  const argv = process.argv.slice(2);
  let amount = DEFAULT_BORROW_USDC_UNITS;
  let skipDeposit = false;
  let skipBorrow = false;
  let skipBridge = false;
  let repay: bigint | 'all' | null = null;
  let withdraw: bigint | 'all' | null = null;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === '--amount') {
      const v = argv[++i];
      if (!v) throw new Error('--amount needs a value');
      amount = BigInt(Math.round(Number(v) * 1_000_000));
    } else if (a === '--skip-deposit') {
      skipDeposit = true;
    } else if (a === '--skip-borrow') {
      skipBorrow = true;
    } else if (a === '--skip-bridge') {
      skipBridge = true;
    } else if (a === '--repay') {
      const v = argv[++i];
      if (!v) throw new Error('--repay needs a value (all | <usdc>)');
      repay = v === 'all' ? 'all' : BigInt(Math.round(Number(v) * 1_000_000));
    } else if (a === '--withdraw') {
      const v = argv[++i];
      if (!v) throw new Error('--withdraw needs a value (all | <sol>)');
      withdraw = v === 'all' ? 'all' : BigInt(Math.round(Number(v) * Number(LAMPORTS_PER_SOL)));
    } else {
      throw new Error(`unknown arg: ${a}`);
    }
  }
  return { amount, skipDeposit, skipBorrow, skipBridge, repay, withdraw };
}

const TOKEN_PROGRAM_ID = new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');
const ASSOCIATED_TOKEN_PROGRAM_ID = new PublicKey('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL');
const COMPUTE_BUDGET_PROGRAM = new PublicKey('ComputeBudget111111111111111111111111111111');
const MAX_COMPUTE_UNITS = 1_400_000;

/**
 * klend-sdk emits a `setComputeUnitLimit(1)` sentinel expecting the caller to
 * patch it post-simulation. Rewrite any such instruction to the provided limit.
 * Returns a new VersionedTransaction keyed to a fresh blockhash.
 */
async function patchComputeUnitLimit(
  connection: Connection,
  tx: VersionedTransaction,
  owner: PublicKey,
  limit: number = MAX_COMPUTE_UNITS,
): Promise<VersionedTransaction> {
  const decompiled = TransactionMessage.decompile(tx.message, {
    addressLookupTableAccounts: [],
  });
  let patched = false;
  const instructions = decompiled.instructions.map((ix) => {
    if (!ix.programId.equals(COMPUTE_BUDGET_PROGRAM)) return ix;
    const data = Buffer.from(ix.data);
    if (data.length >= 5 && data.readUInt8(0) === 2) {
      const newData = Buffer.alloc(5);
      newData.writeUInt8(2, 0);
      newData.writeUInt32LE(limit, 1);
      patched = true;
      return { ...ix, data: newData };
    }
    return ix;
  });
  if (!patched) return tx;
  const { blockhash } = await connection.getLatestBlockhash();
  const message = new TransactionMessage({
    payerKey: owner,
    recentBlockhash: blockhash,
    instructions,
  }).compileToV0Message();
  return new VersionedTransaction(message);
}

function ataFor(mint: PublicKey, owner: PublicKey): PublicKey {
  const [ata] = PublicKey.findProgramAddressSync(
    [owner.toBuffer(), TOKEN_PROGRAM_ID.toBuffer(), mint.toBuffer()],
    ASSOCIATED_TOKEN_PROGRAM_ID,
  );
  return ata;
}

function loadDotEnv(path: string): Record<string, string> {
  const text = readFileSync(path, 'utf-8');
  const out: Record<string, string> = {};
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !line.trim().startsWith('#')) out[m[1]!] = m[2]!;
  }
  return out;
}

function section(title: string): void {
  console.log(`\n━━━ ${title} ${'━'.repeat(Math.max(0, 60 - title.length))}`);
}

function fmtSol(lamports: bigint): string {
  return (Number(lamports) / Number(LAMPORTS_PER_SOL)).toFixed(6);
}

function fmtUsdc(units: bigint): string {
  return (Number(units) / 1e6).toFixed(3);
}

async function fetchSolUsd(): Promise<number> {
  const r = await fetch(
    'https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd',
  );
  const j = (await r.json()) as { solana?: { usd?: number } };
  const usd = j.solana?.usd;
  if (typeof usd !== 'number' || usd <= 0) throw new Error('bad SOL price');
  return usd;
}

async function signAndSend(
  connection: Connection,
  tx: VersionedTransaction,
  signer: Keypair,
  label: string,
  extraSigners: ReadonlyArray<import('@solana/web3.js').Signer> = [],
): Promise<string> {
  tx.sign([signer, ...extraSigners]);
  const sig = await connection.sendRawTransaction(tx.serialize(), {
    skipPreflight: false,
    maxRetries: 3,
  });
  console.log(`  sent ${label}: ${sig}`);
  const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash();
  const conf = await connection.confirmTransaction(
    { signature: sig, blockhash, lastValidBlockHeight },
    'confirmed',
  );
  if (conf.value.err) throw new Error(`${label} failed: ${JSON.stringify(conf.value.err)}`);
  console.log(`  ✓ confirmed ${label}`);
  return sig;
}

async function usdcBalance(connection: Connection, owner: PublicKey): Promise<bigint> {
  const ata = ataFor(new PublicKey(SOLANA_USDC_MINT), owner);
  const info = await connection.getAccountInfo(ata);
  if (!info) return 0n;
  // SPL token account layout: amount at offset 64, u64 little-endian
  const data = info.data;
  return data.readBigUInt64LE(64);
}

async function baseUsdcBalance(address: `0x${string}`): Promise<bigint> {
  const client = createPublicClient({ chain: base, transport: http() });
  return (await client.readContract({
    address: BASE_USDC as `0x${string}`,
    abi: erc20Abi,
    functionName: 'balanceOf',
    args: [address],
  })) as bigint;
}

async function buildMayanBridgeTxForBroadcast(args: {
  mayan: MayanAdapter;
  connection: Connection;
  quote: Quote;
}): Promise<{
  tx: VersionedTransaction;
  extraSigners: import('@solana/web3.js').Signer[];
  orderHash: string | undefined;
  route: string;
}> {
  // The adapter compiles with a placeholder blockhash; swap in a fresh one
  // before broadcast. Works for both SWIFT and FAST_MCTP routes.
  const bundle = await args.mayan.buildBridgeTx(args.quote);
  if (bundle.chain !== 'solana') throw new Error('expected solana bundle');
  const tx = bundle.txs[0];
  const { blockhash } = await args.connection.getLatestBlockhash();
  tx.message.recentBlockhash = blockhash;
  return {
    tx,
    extraSigners: bundle.extraSigners,
    orderHash: bundle.orderHash,
    route: bundle.route,
  };
}

async function pollMayanStatus(
  mayanGetStatus: (h: string) => Promise<'PENDING' | 'SETTLED' | 'REFUNDED'>,
  orderHash: string,
  timeoutMs: number,
): Promise<'SETTLED' | 'REFUNDED' | 'TIMEOUT'> {
  const start = Date.now();
  let last = '';
  while (Date.now() - start < timeoutMs) {
    try {
      const s = await mayanGetStatus(orderHash);
      if (s !== last) {
        console.log(`  status=${s} (t+${Math.round((Date.now() - start) / 1000)}s)`);
        last = s;
      }
      if (s === 'SETTLED') return 'SETTLED';
      if (s === 'REFUNDED') return 'REFUNDED';
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (!msg.includes('404')) console.log(`  status fetch err: ${msg}`);
    }
    await new Promise((r) => setTimeout(r, 5000));
  }
  return 'TIMEOUT';
}

async function main(): Promise<void> {
  const cli = parseCliArgs();
  const webEnv = loadDotEnv(resolve(process.cwd(), 'apps/web/.env.local'));
  const testEnv = loadDotEnv(resolve(process.cwd(), '.env.test.local'));

  const rpc = webEnv.NEXT_PUBLIC_SOLANA_RPC_URL;
  const market = webEnv.NEXT_PUBLIC_KAMINO_MARKET ?? KAMINO_MAIN_MARKET;
  const referrer = webEnv.NEXT_PUBLIC_MAYAN_REFERRER || undefined;
  if (!rpc) throw new Error('missing NEXT_PUBLIC_SOLANA_RPC_URL');

  const solSecret = testEnv.SOLANA_TEST_SECRET;
  const baseAddress = testEnv.BASE_TEST_ADDRESS as `0x${string}` | undefined;
  if (!solSecret) throw new Error('missing SOLANA_TEST_SECRET — run gen-test-wallets.ts');
  if (!baseAddress) throw new Error('missing BASE_TEST_ADDRESS — run gen-test-wallets.ts');

  const signer = Keypair.fromSecretKey(bs58.decode(solSecret));
  const owner = signer.publicKey;
  const connection = new Connection(rpc, 'confirmed');
  const kamino = createKaminoAdapter({ connection, marketAddress: new PublicKey(market) });
  const mayan = createMayanAdapter({ solanaConnection: connection, referrer });

  section('Config');
  console.log(`  RPC        : ${rpc}`);
  console.log(`  market     : ${market}`);
  console.log(`  sol owner  : ${owner.toBase58()}`);
  console.log(`  base recv  : ${baseAddress}`);
  console.log(
    `  mode       : deposit=${!cli.skipDeposit} repay=${cli.repay ?? 'skip'} borrow=${!cli.skipBorrow} bridge=${cli.skipBridge ? 'skip' : fmtUsdc(cli.amount) + ' USDC'} withdraw=${cli.withdraw ?? 'skip'}`,
  );

  const solUsd = await fetchSolUsd();
  const lamports = BigInt(Math.floor((TARGET_COLLATERAL_USD / solUsd) * Number(LAMPORTS_PER_SOL)));
  section('Plan');
  console.log(`  SOL/USD    : $${solUsd}`);
  if (!cli.skipDeposit) {
    console.log(`  deposit    : ${fmtSol(lamports)} SOL (~$${TARGET_COLLATERAL_USD})`);
  } else {
    console.log(`  deposit    : SKIPPED (reusing on-chain collateral)`);
  }
  if (cli.repay) {
    console.log(`  repay      : ${cli.repay === 'all' ? 'ALL' : fmtUsdc(cli.repay) + ' USDC'}`);
  }
  if (!cli.skipBorrow) {
    console.log(`  borrow     : ${fmtUsdc(cli.amount)} USDC`);
  } else {
    console.log(`  borrow     : SKIPPED`);
  }
  if (!cli.skipBridge) {
    console.log(`  bridge     : ${fmtUsdc(cli.amount)} USDC → ${baseAddress}`);
  } else {
    console.log(`  bridge     : SKIPPED`);
  }
  if (cli.withdraw) {
    console.log(`  withdraw   : ${cli.withdraw === 'all' ? 'ALL' : fmtSol(cli.withdraw) + ' SOL'}`);
  }

  const startBal = BigInt(await connection.getBalance(owner));
  console.log(`  balance    : ${fmtSol(startBal)} SOL`);
  if (!cli.skipDeposit && startBal < lamports + 20_000_000n) {
    throw new Error(`insufficient SOL (need ≥ ${fmtSol(lamports + 20_000_000n)})`);
  }

  if (!cli.skipDeposit) {
    section('Step 1 — Kamino DEPOSIT');
    const [depositTxRaw] = await kamino.buildDepositCollateralTx({ owner, lamports });
    if (!depositTxRaw) throw new Error('no deposit tx');
    const depositTx = await patchComputeUnitLimit(connection, depositTxRaw, owner);
    await signAndSend(connection, depositTx, signer, 'deposit');
  } else {
    section('Step 1 — Kamino DEPOSIT (skipped)');
  }
  const obligation0 = await kamino.getObligation(owner);
  console.log(
    `  obligation: collateral=${obligation0 ? fmtSol(obligation0.collateralLamports) : 'null'} SOL, borrowed=${obligation0 ? fmtUsdc(obligation0.borrowedUsdcBaseUnits) : '-'} USDC`,
  );

  if (cli.repay !== null) {
    section('Step 2 — Kamino REPAY');
    const [repayTxRaw] = await kamino.buildRepayTx({ owner, amount: cli.repay });
    if (!repayTxRaw) throw new Error('no repay tx');
    const repayTx = await patchComputeUnitLimit(connection, repayTxRaw, owner);
    await signAndSend(connection, repayTx, signer, 'repay');
    const obligation1 = await kamino.getObligation(owner);
    console.log(
      `  after repay: borrowed=${obligation1 ? fmtUsdc(obligation1.borrowedUsdcBaseUnits) : '-'} USDC`,
    );
  }

  if (!cli.skipBorrow) {
    section(`Step 3 — Kamino BORROW ${fmtUsdc(cli.amount)} USDC`);
    const [borrowTxRaw] = await kamino.buildBorrowTx({
      owner,
      amountUsdc: cli.amount,
    });
    if (!borrowTxRaw) throw new Error('no borrow tx');
    const borrowTx = await patchComputeUnitLimit(connection, borrowTxRaw, owner);
    await signAndSend(connection, borrowTx, signer, 'borrow');
  } else {
    section('Step 3 — Kamino BORROW (skipped)');
  }
  const usdc = await usdcBalance(connection, owner);
  console.log(`  USDC ata balance: ${fmtUsdc(usdc)} USDC`);
  if (!cli.skipBridge && usdc < cli.amount) {
    throw new Error(`expected ≥ ${fmtUsdc(cli.amount)} USDC in wallet, got ${fmtUsdc(usdc)}`);
  }

  let bridgeOutcome: 'ok' | 'skipped' | 'failed' = 'skipped';
  if (!cli.skipBridge) {
    section('Step 4 — Mayan BRIDGE OUT (solana → base)');
    const quote = await mayan.quote({
      fromChain: 'solana',
      toChain: 'base',
      amountUsdc: cli.amount,
      fromAddress: owner.toBase58(),
      toAddress: baseAddress,
    });
    console.log(
      `  quote: minOut=${fmtUsdc(quote.minAmountOut)} USDC, expires=${new Date(quote.expiresAt).toISOString()}`,
    );
    const {
      tx: bridgeTx,
      extraSigners,
      orderHash,
      route,
    } = await buildMayanBridgeTxForBroadcast({
      mayan,
      connection,
      quote,
    });
    console.log(`  route    : ${route} (extra signers: ${extraSigners.length})`);
    if (orderHash) console.log(`  orderHash: ${orderHash}`);
    const bridgeSig = await signAndSend(
      connection,
      bridgeTx,
      signer,
      'mayan bridge-out',
      extraSigners,
    );

    section('Step 5 — Poll Mayan until SETTLED');
    console.log(`  tracking by source sig: ${bridgeSig}`);
    console.log(`  explorer: https://explorer.mayan.finance/swap/${bridgeSig}`);
    const before = await baseUsdcBalance(baseAddress);
    console.log(`  Base USDC before: ${fmtUsdc(before)} USDC`);
    const status = await pollMayanStatus(mayan.getOrderStatus, bridgeSig, 15 * 60 * 1000);
    console.log(`  final status: ${status}`);
    const after = await baseUsdcBalance(baseAddress);
    console.log(`  Base USDC after : ${fmtUsdc(after)} USDC (Δ ${fmtUsdc(after - before)})`);
    bridgeOutcome = status === 'SETTLED' && after - before >= quote.minAmountOut ? 'ok' : 'failed';
  } else {
    section('Step 4/5 — Mayan BRIDGE (skipped)');
  }

  if (cli.withdraw !== null) {
    section(
      `Step 6 — Kamino WITHDRAW ${cli.withdraw === 'all' ? 'ALL' : fmtSol(cli.withdraw) + ' SOL'}`,
    );
    const [withdrawTxRaw] = await kamino.buildWithdrawCollateralTx({
      owner,
      lamports: cli.withdraw,
    });
    if (!withdrawTxRaw) throw new Error('no withdraw tx');
    const withdrawTx = await patchComputeUnitLimit(connection, withdrawTxRaw, owner);
    await signAndSend(connection, withdrawTx, signer, 'withdraw');
    const obligation2 = await kamino.getObligation(owner);
    console.log(
      `  after withdraw: collateral=${obligation2 ? fmtSol(obligation2.collateralLamports) : 'null'} SOL, borrowed=${obligation2 ? fmtUsdc(obligation2.borrowedUsdcBaseUnits) : '-'} USDC`,
    );
    const endBal = BigInt(await connection.getBalance(owner));
    console.log(`  wallet SOL    : ${fmtSol(endBal)} SOL`);
  }

  section('Summary');
  if (bridgeOutcome === 'failed') {
    console.log(`  ✗ bridge step did not settle`);
    process.exitCode = 1;
  } else if (bridgeOutcome === 'ok') {
    console.log('  ✓ OPEN flow succeeded end-to-end');
  }
  if (cli.repay !== null || cli.withdraw !== null) {
    const final = await kamino.getObligation(owner);
    console.log(
      `  final obligation: collateral=${final ? fmtSol(final.collateralLamports) : 'null'} SOL, borrowed=${final ? fmtUsdc(final.borrowedUsdcBaseUnits) : '-'} USDC`,
    );
    const fullyClosed =
      !final || (final.collateralLamports === 0n && final.borrowedUsdcBaseUnits === 0n);
    if (fullyClosed) console.log('  ✓ position fully closed');
  }
}

main().catch((e: unknown) => {
  const msg = e instanceof Error ? (e.stack ?? e.message) : JSON.stringify(e);
  console.error('fatal:', msg);
  process.exit(1);
});
