/**
 * Generate a throwaway Solana keypair + Base (EVM) private key for E2E testing.
 *
 * Writes both secrets to `.env.test.local` at the repo root (gitignored).
 * Prints only the PUBLIC addresses to stdout so secrets don't get captured
 * in terminal history / screenshots.
 *
 * Usage:
 *   pnpm tsx scripts/gen-test-wallets.ts
 *
 * Consumed by: scripts/e2e-broadcast.ts (next step).
 */
import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { Keypair } from '@solana/web3.js';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import bs58 from 'bs58';

const OUT_PATH = resolve(process.cwd(), '.env.test.local');

function main(): void {
  if (existsSync(OUT_PATH) && !process.argv.includes('--force')) {
    console.error(
      `refusing to overwrite ${OUT_PATH}\n` +
        `  pass --force to regenerate (this invalidates the previous test wallet)`,
    );
    process.exit(1);
  }

  const sol = Keypair.generate();
  const solSecret = bs58.encode(sol.secretKey);

  const baseKey = generatePrivateKey();
  const baseAccount = privateKeyToAccount(baseKey);

  const content =
    `# Generated by scripts/gen-test-wallets.ts — DO NOT COMMIT\n` +
    `# Solana (base58-encoded full 64-byte secret key)\n` +
    `SOLANA_TEST_SECRET=${solSecret}\n` +
    `SOLANA_TEST_PUBKEY=${sol.publicKey.toBase58()}\n` +
    `\n` +
    `# Base / EVM (0x-prefixed 32-byte private key)\n` +
    `BASE_TEST_PRIVKEY=${baseKey}\n` +
    `BASE_TEST_ADDRESS=${baseAccount.address}\n`;

  writeFileSync(OUT_PATH, content, { mode: 0o600 });

  console.log(`wrote ${OUT_PATH} (mode 0600)\n`);
  console.log('Public addresses — fund these:');
  console.log(`  Solana : ${sol.publicKey.toBase58()}`);
  console.log(`  Base   : ${baseAccount.address}`);
  console.log('\nSuggested funding:');
  console.log('  Solana : ~0.30 SOL');
  console.log('  Base   : ~0.0003 ETH for gas (roughly $1)');
  console.log('\nSecrets are stored locally only and never printed here.');
}

main();
